
spring:
  security:
    user:
      name: admin
      password: zealow139
  application:
    name: discovery-service
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 30000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Expose Actuator endpoints
  endpoint:
    health:
      show-details: always

