server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/newauthdb
    username: postgres
    password: zealow139
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

auth:
  jwt:
    expiration: 86400000 # 24 hours in ms
    refresh-expiration: 604800000 # 7 days in ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,auditevents
  endpoint:
    health:
      show-details: always
    auditevents:
      access: read_only

logging:
  level:
    org.springframework.security: INFO
    org.codewithzea.auth: DEBUG
